### ISSUE TITLE
Setup And Database

### ISSUE THREAD

**Issue by Elqul** [AtomicLlama/MoviesBackendServer#8]
hello,

how do i setup this server ? and where is the database script ?

Thank you

**Comment by nerdsupremacist** [comment]
Ehm. I don't understand what you mean by database script. This connects to a MongoDB instance we have set up. Which happens to be hard coded for now.

This is a very specialised server solution that is nowhere near production ready. Are you sure you want to run this?

If so install NodeJS. And run npm install and npm start on the Project folder. But the Facebook integration won't run locally, because of the Facebook API. So you can't log in.

**Comment by Elqul** [comment]
yes i want to use it for development without the facebook login.
once i install NodeJS and run npm start this will connect to your own MongoDB. correct ?

**Comment by nerdsupremacist** [comment]
Yes. Exactly it will connect to ours. But why exactly do you want this? It's useless without the Facebook integration.

**Comment by Elqul** [comment]
well , i want to make some changes to this project server wise and try a few things out.

by the way, can you just try to show me the schema flow of the DB. like the table structure so that maybe i can implement my own mongoDB on my server?

**Comment by nerdsupremacist** [comment]
Sure. We have three collections. One that stores all the user information (id, settings), watchlist, that does a mapping all the movies in the users watch lists and subs that does the same thing but for following actors. It's really not much. If you give it a MongoDB instance it will even create the collections itself.
We're not in the business of storing a lot of data.

**Comment by Elqul** [comment]
Alright thank you . i will give it a try
